### ISSUE TITLE
Regarding discussion about local development

### ISSUE THREAD

**Issue by arsham** [KurokuLabs/margo#12]
Having followed [your suggestion](https://github.com/KurokuLabs/margo/pull/6#discussion_r182793691), only changes made in `src/disposa.blue/margo/` are watched and applied. Anything in `src/margo.sh/` is ignored. My folder structure at `$HOME/.config/sublime-text-3/Packages/GoSublime/src` looks like this:
```bash
.
├── disposa.blue
│   └── margo
│       ├── cmd
│       │   ├── margo
│       │   └── margo.sublime
│       ├── cmdpkg
│       │   ├── margo
│       │   └── margosublime
│       └── ...
├── gosublime
│   ├── cmd
│   │   ├── margo
│   │   │   └── main.go
│   │   └── margo_pkg
│   ├── margo
│   └── something-borrowed
└── margo.sh  # <--- mounted folder
    ├── cmd
    │   └── margo.sublime
    │       └── main.go
    ├── cmdpkg
    │   ├── margo
    │   │   └── main.go
    │   └── margosublime
    │       └── main.go
    ├── main.go
    ├── mg
    │   ├── action.go
    │   └── ...
    ├── sublime
    │   └── sublime.go
    └── ...
```
What am I missing here?

Thank you.

**Comment by DisposaBoy** [comment]
I think you're on the wrong branch of GoSublime (you should be on the `development` branch). margo was moved to margo.sh after the transfer of ownership. Compare https://github.com/DisposaBoy/GoSublime/tree/master/src https://github.com/DisposaBoy/GoSublime/tree/development/src
