### ISSUE TITLE
Question regarding contributing to the code

### ISSUE THREAD

**Issue by arsham** [KurokuLabs/margo#4]
I would like to contribute to the plugin. I can help with writing tests, documenting, bug fixing and refactoring code. I appreciate it if you would tell me how is your development flow, and share any architectural documents, or any pointers that could help me start.

Cheers,
Arsham

**Comment by DisposaBoy** [comment]
@arsham Thanks. I'm still in the process of getting the website setup and sorting out the project ownership, etc. but I shouldhopefully get back to you in a week or two.

**Comment by arsham** [comment]
I look forward to it. Cheers.

**Comment by arsham** [comment]
Hi mate, any news on the new website?

**Comment by DisposaBoy** [comment]
Sorry for the late reply - I don't check Github or emails often enough.

[The website](https://margo.sh/) doesn't have any content yet unfortunately.
I need to get the CLA situation sorted out before I can start to accept anything in this repo.
I should get back to you by Tuesday.
In the mean time, feel free to ask any questions here or email me.

**Comment by arsham** [comment]
Thanks mate. I don't have your email address though.

**Comment by DisposaBoy** [comment]
The CLA is already written but not online yet. I'll get it online tomorrow and then I can start reviewing your PR.

**Comment by DisposaBoy** [comment]
The CLA is now online at https://cla.kuroku.io/ after you sign it, the bot should clear your PRs for review.
