### ISSUE TITLE
Question: is there a chance TypeCmd receives nil

### ISSUE THREAD

**Issue by arsham** [KurokuLabs/margo#8]
At [this](https://github.com/KurokuLabs/margo/blob/48c3658f0eb10ad0ea1e436304fb0f8403736913/mg/builtins.go#L57) line (and in subsequent *Cmd methods), is there a chance to receive a `nil` pointer as input? I've traced it back (one branch of callers) to [this](https://github.com/KurokuLabs/margo/blob/48c3658f0eb10ad0ea1e436304fb0f8403736913/mg/cmd.go#L88) line. If by any chance the `Output` is nil, the *Cmd methods will panic. Is it worth pursuing? We can create a ticket and fix it in a future release.

We can do one of the following:
1. Return the object and an error.
2. Accept values instead of a pointers.
3. Return an empty `State` object if the input is nil. I'm not sure about this option as I'm still studying the code.

**Comment by DisposaBoy** [comment]
All bultins are called by https://github.com/KurokuLabs/margo/blob/48c3658f0eb10ad0ea1e436304fb0f8403736913/mg/cmd.go#L123 so there's no chance the input can be invalid.

There are (should be) no nil pointers in anything passed down to/through reducers. Here `anything` means `*Ctx`, `*State`, `*BultinCmdCtx`, `etc.`. 

`type CmdOutputWriter` has internal state (e.g. a mutex) so it can't be a value.
