### ISSUE TITLE
Configure build tags to tests

### ISSUE THREAD

**Issue by eminetto** [KurokuLabs/margo#81]
How can I configure the test command to add build flags, like:

```go test -tags dev -failfast -v '-test.run=^TestAddInvite$'```

**Comment by DisposaBoy** [comment]
Add them to the `golang.TestCmds` reducer's `TestArgs` .

See example https://github.com/DisposaBoy/GoSublime/blob/development/src/margo.sh/extension-example/extension-example.go#L136
